### ISSUE TITLE
Log bug in 1.16.5

### ISSUE THREAD

**Issue by lastomega-001** [MModding/archeon#15]
In version 1.16.5,this mod will output a large amount of "[Render thread/INFO]: [net.aethyus.archeon.procedures.OSTManagerProcedure:executeProcedure:108]: 0.0" in the log. Can this bug be fixed?
![Screenshot 2024-10-06 131952](https://github.com/user-attachments/assets/55f3a150-859c-42df-bfcd-c7f46b0ec191)

**Comment by FirstMegaGame4** [comment]
Hi!

This repository is not the one for Archeon 1.16.5! The 1.16.5 is now unsupported, plus this bug is probably not caused directly by us, but by MCreator, as that old version was made with it.

**Comment by FirstMegaGame4** [comment]
(Stated this issue as not planned but if we find what is causing that we'll release a small patch for 1.16.5 as it's still an annoying bug)

**Comment by Aethyus** [comment]
I confirm, it's the first time I see this, but since we left MCreator for a while now, I can't do anything about it, sorry

**Comment by lastomega-001** [comment]
> I confirm, it's the first time I see this, but since we left MCreator for a while now, I can't do anything about it, sorry

I solved this problem, you just need to delete the code on the line 108 of "Archeon-Old-archeon-old\src\main\java\net\aethyus\archeon\procedures\OSTManagerProcedure.java",
`System.out.println((entity.getCapability(ArcheonModVariables.PLAYER_VARIABLES_CAPABILITY, null)
					.orElse(new ArcheonModVariables.PlayerVariables())).soundtimer);
`
This way, the log won't output this anymore
